signals:
- momentum
- reversal
- beta
ic: .05
signal-combinator: mean
constraints:
- full-investment
- long-only
- no-buying-on-margin
- unit-beta
gamma: 350
decimal-places: 4
data-date: 2025-10-30
ignore-tickers:
- MONDQ
- VELO
- BGXXQ
- PSTX.CVR
broker: test
